In [29]:
import numpy as np 

In [30]:
(1.2*10**(-26))**(1/3)

2.2894284851066664e-09

In [31]:
x_arr = np.array([0.84375, 0.84375,0.84375,0.8125])
y_arr = np.array([0.3125,0.3125,0.28125,0.3125])
z_arr = np.array([0.15625,0.21875,0.1875,0.1875])

order = [0,1,2,3]

In [32]:

x0 = x_arr[order[0]]
x1 = x_arr[order[1]]
x2 = x_arr[order[2]]
x3 = x_arr[order[3]]

y0 = y_arr[order[0]]
y1 = y_arr[order[1]]
y2 = y_arr[order[2]]
y3 = y_arr[order[3]]

z0 = z_arr[order[0]]
z1 = z_arr[order[1]]
z2 = z_arr[order[2]]
z3 = z_arr[order[3]]


In [33]:
J = np.array(
    [
        [x1-x0, y1-y0, z1-z0],
        [x2-x0, y2-y0, z2-z0],
        [x3-x0, y3-y0, z3-z0]
    ]
)

In [34]:
refbasis = np.array(
    [
        [-1, 1,0,0],
        [-1, 0, 1, 0],
        [-1,0,0,1]
    ]
)

In [35]:
Jinv = np.linalg.inv(J)
Jdet = np.linalg.det(J)

In [36]:
Jadj = Jinv * Jdet 

In [37]:
Jadj 

array([[-0.00097656,  0.        ,  0.00195313],
       [-0.00097656,  0.00195313,  0.        ],
       [-0.00097656, -0.        , -0.        ]])

In [38]:
Jinv 

array([[ 16.,  -0., -32.],
       [ 16., -32.,  -0.],
       [ 16.,   0.,   0.]])

In [39]:
substiff = np.transpose((Jadj @ refbasis)) @ (Jadj @ refbasis) / (Jdet * 6) 

In [40]:
substiff = substiff

In [41]:
substiff 

array([[-0.0078125 , -0.00260417,  0.00520833,  0.00520833],
       [-0.00260417, -0.0078125 ,  0.00520833,  0.00520833],
       [ 0.00520833,  0.00520833, -0.01041667, -0.        ],
       [ 0.00520833,  0.00520833, -0.        , -0.01041667]])

In [42]:
np.linalg.inv(substiff)

LinAlgError: Singular matrix